#!/usr/bin/env node

import { styleText } from 'node:util'

import { replaceInFileSync } from 'replace-in-file'

const options = {
  files: 'dist/**/*.js',
}
const result = [
  replaceInFileSync({
    ...options,
    from: /#\/src\//g,
    to: '#/dist/',
  }),
  replaceInFileSync({
    ...options,
    from: /\.\/src\/apps\//g,
    to: './dist/apps/',
  }),
]

const changedFiles = 10 //result.flat().filter((file) => file.hasChanged).length
const messageFormat = changedFiles ? 'green' : 'yellow'
const message = changedFiles ? `${changedFiles} file(s) were changed` : 'No files were changed'

// eslint-disable-next-line no-console
console.log(
  `Replacing '${options.from}' with '${options.to}'\n${styleText(messageFormat, message)}`,
)
